(() => {
 const zone='Asia/Seoul',dateKey=value=>new Intl.DateTimeFormat('sv-SE',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value)),today=()=>dateKey(Date.now());
 const make=(tag,text,cls)=>{const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el;};
 const button=(text,fn)=>{const el=make('button',text,'dash-button');el.type='button';el.onclick=fn;return el;};
 const seconds=value=>{value=Math.round(value||0);return Math.floor(value/60)+'분 '+value%60+'초';};
 const linked=()=>fbState.connected&&latestData['main-page']?.url&&latestData['main-page'].linked!==false;
 async function get(path,url,version){const token=await ensureFreshToken();if(version!==connectionVersion)throw Error('프로젝트가 변경되었습니다.');const r=await fetch(url+'/'+path+'.json',{headers:{Authorization:'Bearer '+token}});if(!r.ok)throw Error('데이터를 불러오지 못했습니다.');return r.json();}
 function dialog(title){const el=make('dialog',undefined,'dash-dialog'),head=make('div',undefined,'dash-heading'),close=button('닫기',()=>{el.close();el.remove();});head.append(make('h3',title),close);el.append(head);document.body.append(el);el.addEventListener('cancel',()=>el.remove());el.showModal();return el;}
 window.mountProjectDashboard=function(page,panel,main){
  const version=connectionVersion,url=fbState.databaseURL;
  if(page==='schedule')mountSchedule(panel,version,url);else mountAnalytics(panel,main,version,url);
 };
 function mountSchedule(panel,version,url){
  let shown=today().slice(0,7),dates=latestData['callendar-setting']?.dates||{};
  const card=make('section',undefined,'dash-card'),heading=make('div',undefined,'dash-heading'),label=make('h3'),days=make('div',undefined,'schedule-grid'),status=make('p','날짜를 눌러 작업가능·마감임박·휴일을 설정하세요. 과거 날짜는 자동으로 마감됩니다.','dash-muted');
  const change=delta=>{const d=new Date(shown+'-01T12:00:00+09:00');d.setUTCMonth(d.getUTCMonth()+delta);shown=dateKey(d).slice(0,7);render();};
  heading.append(button('이전 달',()=>change(-1)),label,button('다음 달',()=>change(1)));card.append(heading,status,days);panel.append(card);
  function render(){label.textContent=shown.replace('-','년 ')+'월';days.replaceChildren();for(const name of ['일','월','화','수','목','금','토'])days.append(make('div',name,'schedule-weekday'));
   const [year,month]=shown.split('-').map(Number),first=new Date(Date.UTC(year,month-1,1)).getUTCDay(),count=new Date(Date.UTC(year,month,0)).getUTCDate();for(let i=0;i<first;i++)days.append(make('div'));
   for(let day=1;day<=count;day++){const key=shown+'-'+String(day).padStart(2,'0'),past=key<today(),value=past?'closed':dates[key]||'available';const el=button('',()=>choose(key));el.className='schedule-day '+value;el.append(make('strong',String(day)),make('small',({available:'작업가능',deadline:'마감임박',holiday:'휴일',closed:'마감'})[value]));el.disabled=past;el.setAttribute('aria-label',key+' '+el.textContent);days.append(el);}
  }
  function choose(key){const modal=dialog(key+' 일정'),note=make('p','저장할 상태를 선택하세요.');modal.append(note);for(const [type,label] of [['available','작업가능'],['deadline','마감임박'],['holiday','휴일']])modal.append(button(label,async()=>{
   if(version!==connectionVersion||!linked())return;modal.querySelectorAll('button').forEach(b=>b.disabled=true);
   try{await fbSet('callendar-setting/dates/'+key,type);const token=await ensureFreshToken();const r=await fetch(url+'/.settings/rules.json',{headers:{Authorization:'Bearer '+token}});if(!r.ok)throw Error('일정 공개 읽기 권한 확인 실패');const rules=await r.json();rules.rules['callendar-setting']={...(rules.rules['callendar-setting']||{}),'.read':true};const put=await fetch(url+'/.settings/rules.json',{method:'PUT',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify(rules)});if(!put.ok)throw Error('메인페이지 일정 읽기 설정 실패');if(version!==connectionVersion)return;dates[key]=type;render();modal.close();modal.remove();status.textContent=key+' '+label+' 저장 완료';}catch(e){note.textContent=e.message;modal.querySelectorAll('button').forEach(b=>b.disabled=false);}
  }));}
  render();get('callendar-setting',url,version).then(data=>{if(version===connectionVersion&&panel.isConnected){dates=data?.dates||{};render();}}).catch(e=>status.textContent=e.message);
 }
 function metric(label,value,detail){const card=make('div',undefined,'dash-card dash-metric');card.append(make('span',label),make('strong',value));if(detail)card.append(make('small',detail));return card;}
 function chart(title,labels,series){const card=make('section',undefined,'dash-card');card.append(make('h3',title));const NS='http://www.w3.org/2000/svg',svg=document.createElementNS(NS,'svg');svg.setAttribute('viewBox','0 0 600 240');svg.setAttribute('role','img');svg.setAttribute('aria-label',title);const max=Math.max(1,...series.flatMap(s=>s.values));
  for(let i=0;i<4;i++){const y=195-i*55,line=document.createElementNS(NS,'line');for(const [k,v] of Object.entries({x1:38,x2:590,y1:y,y2:y,stroke:'#e9e2ee'}))line.setAttribute(k,v);svg.append(line);const t=document.createElementNS(NS,'text');t.setAttribute('x','3');t.setAttribute('y',String(y+4));t.setAttribute('font-size','10');t.textContent=Math.round(max*i/3);svg.append(t);}
  series.forEach(s=>{const line=document.createElementNS(NS,'polyline');line.setAttribute('points',s.values.map((v,i)=>(40+i*540/Math.max(1,labels.length-1))+','+(195-v/max*165)).join(' '));line.setAttribute('fill','none');line.setAttribute('stroke',s.color);line.setAttribute('stroke-width','2.5');svg.append(line);s.values.forEach((v,i)=>{const dot=document.createElementNS(NS,'circle');dot.setAttribute('cx',40+i*540/Math.max(1,labels.length-1));dot.setAttribute('cy',195-v/max*165);dot.setAttribute('r','3');dot.setAttribute('fill',s.color);const tip=document.createElementNS(NS,'title');tip.textContent=labels[i]+' '+s.name+' '+v;dot.append(tip);svg.append(dot);});});
  labels.forEach((label,i)=>{if(i%Math.ceil(labels.length/6)&&i!==labels.length-1)return;const t=document.createElementNS(NS,'text');t.setAttribute('x',40+i*540/Math.max(1,labels.length-1));t.setAttribute('y','220');t.setAttribute('text-anchor','middle');t.setAttribute('font-size','10');t.textContent=label;svg.append(t);});card.append(svg,make('p',series.map(s=>s.name+' '+s.values.reduce((a,b)=>a+b,0)).join(' · '),'dash-muted'));return card;
 }
 function bars(title,rows){const card=make('section',undefined,'dash-card');card.append(make('h3',title));if(!rows.length)card.append(make('p','아직 측정된 기록이 없습니다.','dash-muted'));for(const row of rows){const head=make('div',undefined,'dash-heading');head.append(make('span',row.label),make('strong',row.value));const bar=make('div',undefined,'dash-bar'),fill=make('i');fill.style.width=Math.min(100,row.percent)+'%';bar.append(fill);card.append(head,bar);}return card;}
 function mountAnalytics(panel,main,version,url){
  const tools=make('div',undefined,'dash-heading'),status=make('p','최근 30일 · 한국시간 기준','dash-muted'),body=make('div',undefined,'dash-body');let data={},loading=false;
  tools.append(status,button('새로고침',refresh),button('내역 초기화',async()=>{if(!confirm('방문 기록, 브라우저 식별값, 누적 카운터를 모두 초기화할까요?'))return;if(version!==connectionVersion||!linked())return;try{await fbDeletePath('analytics');await refresh();status.textContent='분석 내역을 초기화했습니다.';}catch(e){status.textContent=e.message;}}));
  panel.append(tools,make('p','브라우저 ID 기준 · 5초 이상 방문부터 기록합니다. 새 방문 기록을 저장할 때 30일이 지난 상세 기록과 식별값을 정리하며, 누적 카운터는 유지합니다.','dash-muted'),body);
  if(latestData._artmug?.analyticsVersion!==3){const setup=button('브라우저 분석 설정',async()=>{if(!confirm('현재 프로젝트에 익명 방문 인증과 30일 보관 분석 규칙을 설정할까요? 기존 분석 경로의 규칙을 교체합니다.'))return;setup.disabled=true;try{await configureBrowserAnalytics(version);setup.remove();status.textContent='브라우저 분석 설정 완료';await refresh();}catch(e){status.textContent=e.message;setup.disabled=false;}});tools.append(setup);}
  async function refresh(){if(loading||version!==connectionVersion||!linked())return;loading=true;try{const result=await get('analytics',url,version);if(version!==connectionVersion||!body.isConnected)return;data=result||{};data.totals=Object.values(data.counters||{}).reduce((a,r)=>({visitors:a.visitors+(r.visitors||0),pageViews:a.pageViews+(r.pageViews||0)}),{visitors:0,pageViews:0});render();}catch(e){status.textContent=e.message;}finally{loading=false;}}
  function render(){body.replaceChildren();const sessions=Object.values(data.sessions||{}).filter(s=>s.startedAt>=Date.now()-30*86400000),day=sessions.filter(s=>dateKey(s.startedAt)===today()),n=sessions.length,percent=v=>n?(v/n*100).toFixed(1)+'%':'0%';
   const first=make('div',undefined,'dash-grid three'),todayCard=metric('당일 페이지 뷰',String(day.length),'PC '+day.filter(s=>s.device==='pc').length+' · 모바일 '+day.filter(s=>s.device==='mobile').length+' · 의뢰게시판 '+day.filter(s=>s.source==='board').length);todayCard.append(button('상세보기',()=>details(sessions)));first.append(metric('총 방문자 수',String(data.totals?.visitors||0),'30일 이내 같은 브라우저 중복 제외'),metric('총 페이지 뷰',String(data.totals?.pageViews||0),'5초 이상 방문 누적'),todayCard);
   const second=make('div',undefined,'dash-grid four');second.append(metric('문의 양식 복사율',percent(sessions.filter(s=>s.copied).length)),metric('신규 방문자 비율',percent(sessions.filter(s=>s.newVisitor).length)),metric('평균 체류 시간',seconds(n?sessions.reduce((a,s)=>a+s.seconds,0)/n:0)),metric('평균 로드시간',(n?sessions.reduce((a,s)=>a+s.loadMs,0)/n/1000:0).toFixed(2)+'초'));
   const hours=Array.from({length:24},()=>new Set());sessions.forEach(s=>hours[Number(new Intl.DateTimeFormat('en-GB',{timeZone:zone,hour:'2-digit',hourCycle:'h23'}).format(new Date(s.startedAt)))].add(s.browserId));
   const dates=Array.from({length:30},(_,i)=>dateKey(Date.now()-(29-i)*86400000)),counts=dates.map(d=>sessions.filter(s=>dateKey(s.startedAt)===d)),charts=make('div',undefined,'dash-grid two');charts.append(chart('시간대별 방문자 · 최근 30일',hours.map((_,i)=>i+'시'),[{name:'방문자',color:'#9059bb',values:hours.map(s=>s.size)}]),chart('일별 방문 추이 · 최근 30일',dates.map(d=>d.slice(5)),[{name:'방문자',color:'#5f3783',values:counts.map(s=>new Set(s.map(x=>x.browserId)).size)},{name:'페이지 뷰',color:'#c392e7',values:counts.map(s=>s.length)}]));
   const flow=[['hero','상단 프로필'],['calendar','일정'],['notice','공지사항'],['about','작가소개'],['portfolio','포트폴리오'],['request','신청양식']].map(([key,label])=>{const value=sessions.filter(s=>s.sections?.[key]).length;return {label,value:value+'회 · '+percent(value),percent:n?value/n*100:0};});const ranks=new Map();sessions.forEach(s=>Object.entries(s.portfolio||{}).forEach(([key,row])=>{const old=ranks.get(key)||{...row,count:0};old.count+=row.count;ranks.set(key,old);}));const sorted=[...ranks.values()].sort((a,b)=>b.count-a.count),tables=make('div',undefined,'dash-grid two');tables.append(bars('스크롤 도달률',flow),bars('카테고리 조회 순위',sorted.map((r,i)=>({label:(i+1)+'위 · '+(r.kind==='video'?'영상':'이미지')+' — '+r.title,value:r.count+'회',percent:r.count/(sorted[0]?.count||1)*100}))));const works=new Map();sessions.forEach(session=>Object.entries(session.portfolioItems||{}).forEach(([key,row])=>{const item=works.get(key)||{...row,count:0};item.count+=row.count||0;works.set(key,item);}));
   const ranked=[...works.values()].sort((a,b)=>b.count-a.count),extra=make('div',undefined,'dash-grid two');
   extra.append(bars('포트폴리오별 노출 순위',ranked.map((r,i)=>({label:(i+1)+'위 · '+(r.kind==='video'?'영상':'이미지')+' — '+r.title,value:r.count+'회',percent:r.count/(ranked[0]?.count||1)*100}))),bars('스크롤 깊이',[25,50,75,100].map(depth=>{const count=sessions.filter(s=>s.scrollMeasured&&s.maxScrollDepth>=depth).length;return {label:depth+'% 도달',value:count+'회 · '+percent(count),percent:n?count/n*100:0};})));
   body.append(first,second,make('p','복사율은 버튼 클릭 기준입니다. 체류시간은 접속부터 탭이 보이는 시간을 합산합니다. 작품 노출은 화면에 보인 작품을 방문당 1회 기록합니다.','dash-muted'),charts,tables,extra);
  }
  function details(sessions){const modal=dialog('방문 상세 내역 · 한국시간'),filter=make('input');filter.type='date';filter.value=today();filter.min=dateKey(Date.now()-29*86400000);filter.max=today();const wrap=make('div',undefined,'dash-table-wrap');const mode=make('select');for(const [value,label] of [['all','전체 방문'],['new','신규 방문자']]){const o=make('option',label);o.value=value;mode.append(o);}modal.append(filter,mode,wrap);const draw=()=>{wrap.replaceChildren();const table=make('table'),head=make('tr');['접속 시간','브라우저 ID','환경','체류시간','신규','의뢰게시판','복사 버튼','최대 스크롤'].forEach(x=>head.append(make('th',x)));table.append(head);const rows=sessions.filter(s=>dateKey(s.startedAt)===filter.value&&(mode.value==='all'||s.newVisitor)).sort((a,b)=>b.startedAt-a.startedAt);for(const s of rows){const row=make('tr');[new Intl.DateTimeFormat('ko-KR',{timeZone:zone,hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date(s.startedAt)),s.browserId,s.device==='mobile'?'모바일':s.device==='pc'?'PC':'확인 불가',seconds(s.seconds),s.newVisitor?'신규':'재방문',s.source==='board'?'예':s.source==='unknown'?'확인 불가':'아니요',s.copied?'클릭':'—',s.scrollMeasured?(s.maxScrollDepth||0)+'%':'미측정'].forEach(x=>row.append(make('td',x)));table.append(row);}wrap.append(table);if(!rows.length)wrap.append(make('p','이 날짜의 기록이 없습니다.'));};filter.onchange=draw;mode.onchange=draw;draw();}
  refresh();
  const timer=setInterval(()=>{if(!body.isConnected||version!==connectionVersion){clearInterval(timer);return;}if(!document.hidden&&panel.classList.contains('active'))refresh();},15000);
 }
})();
